### ISSUE TITLE
Admin panel in dev env : no css/js

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius-Standard#113] opened 2016-08-18 10:57 UTC
Hi
When in dev environment,  assets are being retrieved without the `app_dev.php` part so it fails miserably — styles and js return 404 or 500 and the admin panel is not usable

![screen shot 2016-08-18 at 12 55 41](https://cloud.githubusercontent.com/assets/1944007/17771421/19975db6-6543-11e6-9783-2b652a2d5da8.png)

Apart from `sylius:install`, is there anything that we need to do/configure for this to work ? Thanks !

**Comment by lchrusciel** [comment] 2016-08-18 12:39
Our main support channel is stackoverflow. Please, ask such a question there under a sylius tag.

**Comment by tchapi** [comment] 2016-08-18 13:34
Alright — https://stackoverflow.com/questions/39019290/sylius-standard-admin-panel-no-css-js?noredirect=1#comment65389341_39019290 if you want to have a look, thanks !

**Comment by tchapi** [comment] 2016-08-18 13:51
But @lchrusciel I believe this is a bug, since css and js files should not depend on the production database in a dev environment ...

**Comment by gorkalaucirica** [comment] 2016-11-26 10:37
Could not reproduce following installation steps:

![captura de pantalla 2016-11-26 a las 11 35 25](https://cloud.githubusercontent.com/assets/1749891/20639767/8b6629a4-b3cc-11e6-9bdd-f35bae64041d.png)

Even though the profiler says it's alpha1 I have installed alpha2

**Comment by pjedrzejewski** [comment] 2016-11-26 11:52
This was probably issue with not running "npm run gulp". Closing as it should not be relevant anymore.

**Closed by pjedrzejewski** 2016-11-26 11:52 UTC
