### ISSUE TITLE
Can't build docker

### ISSUE THREAD

**Issue by moezkorkmaz** [Sylius/Sylius-Standard#596] opened 2021-07-23 15:18 UTC
PHP version needed >=7.4
Actual PHP version in container 7.3

**Comment by christopheblin** [comment] 2021-08-06 06:55
A little more details : changing the version from 7.3 to 7.4 is not enough to have the docker build succeed

    #6 24.15 configure: error: unrecognized options: --with-jpeg-dir, --with-png-dir, --with-webp-dir, --with-freetype-dir

have a look to https://github.com/docker-library/php/issues/912 to solve this 

    docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype

but then another error ...

    #6 25.78 configure: error: unrecognized options: --with-libzip

have a look to https://github.com/laradock/laradock/issues/2453#issue-544213537

    docker-php-ext-configure zip

then, I remove composer.lock since it is not part of the git (it should work only with composer.json anyway)

    COPY composer.json symfony.lock ./

But then it fails on composer install (I removed --no-suggest)

```
=> ERROR [sylius_php 10/20] RUN set -eux;  composer install --prefer-dist --no-autoloader --no-scripts --no-progress;  composer clear-ca  16.9s
------                                                                                                                                           
 > [sylius_php 10/20] RUN set -eux;     composer install --prefer-dist --no-autoloader --no-scripts --no-progress;      composer clear-cache:    
#15 0.329 + composer install --prefer-dist --no-autoloader --no-scripts --no-progress                                                            
#15 0.564 No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.                                                                                                                          
#15 0.565 Loading composer repositories with package information                                                                                 
#15 3.697 Updating dependencies
#15 16.70 Killed
```

I tried

    # https://getcomposer.org/doc/03-cli.md#composer-memory-limit
    ENV COMPOSER_MEMORY_LIMIT=-1

But the same error occurs -> I'm out of ideas ...

**Comment by christopheblin** [comment] 2021-08-06 07:37
A bit more porgress thanks to https://stackoverflow.com/a/50770267/1545567

Increasing the Docker desktop RAM to 3Go now results in successfull build for sylius_php and sylius_nginx

I'll make a PR

**Comment by vasilvestre** [comment] 2021-08-13 16:16
Duplicate of https://github.com/Sylius/Sylius-Standard/issues/437 ?

**Comment by lchrusciel** [comment] 2021-09-14 13:39
Hey folks, can you test #605? If it will solve your issue, I can release a new version of Sylius-Standard

**Comment by vasilvestre** [comment] 2021-09-15 08:46
> Hey folks, can you test #605? If it will solve your issue, I can release a new version of Sylius-Standard

It's not working, I've tried to use master branch (as the #605 is merged) and there's a merge conflict in dockerfile D:
https://github.com/Sylius/Sylius-Standard/blob/master/Dockerfile#L81

<<<<<<< HEAD
    composer install --prefer-dist --no-autoloader --no-scripts --no-progress; \
    composer clear-cache
=======
	composer install --prefer-dist --no-autoloader --no-scripts --no-progress; \
	composer clear-cache
>>>>>>> 1.10

**Comment by Fabiomad85** [comment] 2021-11-12 08:22
I have the same issue. Any Help? thanks

**Comment by lchrusciel** [comment] 2021-11-19 14:59
Should be fixed already on master branch

**Closed by lchrusciel** 2021-11-19 14:59 UTC
