### ISSUE TITLE
ERROR , Bad credentials.

### ISSUE THREAD

**Issue by christiankasse** [Sylius/Sylius-Standard#299] opened 2018-11-22 17:33 UTC
can I have the default login after installation to access the admin?

when i try to go to` localhost:8000/admin` I am redirected to `/login `where I pass **sylius** for password, I am denied access saying ERROR Bad credentials.

**Comment by CoderMaggie** [comment] 2018-11-23 07:43
Duplicate of https://github.com/Sylius/Sylius/issues/9954

**Closed by CoderMaggie** 2018-11-23 07:43 UTC
